language: cpp

jobs:
  include:
    - name: "Linux GCC"
      os: linux
      dist: jammy
      compiler: gcc
      script:
        - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        - cmake --build build --config Release --parallel
#        - ctest --test-dir build --output-on-failure

    - name: "Windows MSVC"
      os: windows
      script:
        - cmake -S . -B build -G "Visual Studio 17 2022" -A x64
        - cmake --build build --config Release --parallel
#        - ctest --test-dir build --build-config Release --output-on-failure